<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:tns="ws/dealerposinterface/service"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DealerPosInterface"
	targetNamespace="ws/dealerposinterface/service"
	xmlns:accounts="ws/dealerposinterface/service">
	
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="ws/dealerposinterface/service"
				schemaLocation="../DealerPosInterface.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>



	<wsdl:message name="decisionRequest">
		<wsdl:part element="tns:DecisionRequest" name="DecisionRequest">
		</wsdl:part>
	</wsdl:message>

	<wsdl:message name="decisionResponse">
		<wsdl:part element="tns:DecisionResponse" name="DecisionResponse">
		</wsdl:part>
	</wsdl:message>

	<wsdl:portType name="DealerPosInterfaceService">
		<wsdl:operation name="GetDecision">
			<wsdl:documentation> Retrieve the current status of a given proposal using
				the internal proposal ID. 
			</wsdl:documentation>
			<wsdl:input message="tns:decisionRequest">
			</wsdl:input>
			<wsdl:output message="tns:decisionResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="DealerPosInterfaceServiceSOAPBinding"
		type="tns:DealerPosInterfaceService">

		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetDecision">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>

	<wsdl:service name="DealerPosInterfaceService">
		<wsdl:port
			binding="tns:DealerPosInterfaceServiceSOAPBinding"
			name="DealerPosInterfaceService">
			<soap:address
				location="http://localhost:8080/apache-cfx-demo/DealerPosInterface"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>