package ws.dealerposinterface.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-27T20:00:51.310+05:30
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "DealerPosInterfaceService",
                  wsdlLocation = "file:/C:/soap/Soap+cxf/DealerPosInterface/DealerPosInterfaceService/src/main/resources/wsdl/DealerPosInterface.wsdl",
                  targetNamespace = "ws/dealerposinterface/service")
public class DealerPosInterfaceService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("ws/dealerposinterface/service", "DealerPosInterfaceService");
    public final static QName DealerPosInterfaceService = new QName("ws/dealerposinterface/service", "DealerPosInterfaceService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/soap/Soap+cxf/DealerPosInterface/DealerPosInterfaceService/src/main/resources/wsdl/DealerPosInterface.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DealerPosInterfaceService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/soap/Soap+cxf/DealerPosInterface/DealerPosInterfaceService/src/main/resources/wsdl/DealerPosInterface.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DealerPosInterfaceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DealerPosInterfaceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DealerPosInterfaceService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DealerPosInterfaceService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DealerPosInterfaceService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DealerPosInterfaceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DealerPosInterfaceService
     */
    @WebEndpoint(name = "DealerPosInterfaceService")
    public DealerPosInterfaceService getDealerPosInterfaceService() {
        return super.getPort(DealerPosInterfaceService, DealerPosInterfaceService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DealerPosInterfaceService
     */
    @WebEndpoint(name = "DealerPosInterfaceService")
    public DealerPosInterfaceService getDealerPosInterfaceService(WebServiceFeature... features) {
        return super.getPort(DealerPosInterfaceService, DealerPosInterfaceService.class, features);
    }

}
