package ws.dealerposinterface.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-27T20:00:51.266+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "ws/dealerposinterface/service", name = "DealerPosInterfaceService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DealerPosInterfaceService {

    /**
     * Retrieve the current status of a given proposal using
     * 				the internal proposal ID. 
     * 			
     */
    @WebMethod(operationName = "GetDecision")
    @WebResult(name = "DecisionResponse", targetNamespace = "ws/dealerposinterface/service", partName = "DecisionResponse")
    public DecisionResponse getDecision(

        @WebParam(partName = "DecisionRequest", name = "DecisionRequest", targetNamespace = "ws/dealerposinterface/service")
        DecisionRequest decisionRequest
    );
}
